# Generated by Django 4.0.4 on 2022-05-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='insertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('company_id', models.CharField(max_length=200)),
                ('client_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
